### ISSUE TITLE
Kia Niro Kona 64 kw

### ISSUE THREAD

**Issue by Frankomand** [JejuSoul/OBD-PIDs-for-HKMC-EVs#36]
Hey
I have re-written  some of the data to fit Engine_Link IOS to my own preference.
In the test file all works but SOH
If anyone is interested in the rest, i will ( try ) to convert it fully to Engine_Link IOS
[Niro_EV.txt](https://github.com/JejuSoul/OBD-PIDs-for-HKMC-EVs/files/2989063/Niro_EV.txt)

Please rename to .csv
Cu
Frank

**Comment by piec2** [comment]
Hi Frank, did you manage to confirm the Charging PID was working?: 
7E4220101,Charging HV,0,1,V,{j:7}

I never got it to work when charging my Kona because that bit is always '1' whether I'm charging or not. I had to use the following calculated PID: 
val{000_BMS Main Relay}-val{000_BMS Ignition}

However I haven't had the chance to confirm with a Niro EV owner yet.

**Comment by Frankomand** [comment]
Hey
Try this it will ( should ) show KW both ways - i can´t test it my Ipad is broken so running Torque at the moment.

220101,Energy Draw,-90,90,kW,val{000_Battery Current}*val{000_Battery DC Voltage}/1000,7E4

Cu
Frank

**Comment by plord12** [comment]
> Hi Frank, did you manage to confirm the Charging PID was working?:
> 7E4220101,Charging HV,0,1,V,{j:7}
> 
> I never got it to work when charging my Kona because that bit is always '1' whether I'm charging or not. I had to use the following calculated PID:
> val{000_BMS Main Relay}-val{000_BMS Ignition}
> 
> However I haven't had the chance to confirm with a Niro EV owner yet.

Interesting - on my Kona I've started to use only ay ( ay = 0x0D when normal driving and 0x09 when charging ).

EVNotify is another source of info - see https://github.com/EVNotify/EVNotify/blob/master/app/www/components/cars/KONA_EV.vue

**Comment by Frankomand** [comment]
How do i email you - I have 5 photos 10 MB - Please consider the photos privat, and do not make them public :-)

Cu
Frank

**Comment by piec2** [comment]
> How do i email you - I have 5 photos 10 MB - Please consider the photos privat, and do not make them public :-)
> 
> Cu
> Frank

Hi Frank, you can email me at piec2@yahoo.com
I'll post here tomorrow the results of my testing for all the bits of 'ay'.
The EnergyDraw formula above works fine on my Kona :-)

**Comment by piec2** [comment]
Hi guys,
I posted on Google drive the analysis of the various bytes related to the charging at:
https://docs.google.com/spreadsheets/d/1JyJnXh7DOvzTl0cbWZRpW9qB_OgEOM-w_XOiAY_a64o/edit?usp=sharing
Looks like 0x09 can occur in other conditions than charging, namely:
- at rest but on Accessories mode
- connected J1772 but not charging 

I've put in the file what I think could be used for detecting that the vehicule is charging (and also when its done charging since the value will go back to zero).  I tested the first one and can confirm that works (using BMS Ignition and BMS relay).  I still have to test the second one.

**Comment by Frankomand** [comment]
Hey,
What plugtype do you use in your country ?
Frank

**Comment by Frankomand** [comment]
Hey
Tested the Torque files on E Soul 64 kw today - works fine :-)
Frank

**Comment by JejuSoul** [comment]
-
Am closing this issue because I have started a new issue on this topic which links back here.
